# Generated by Django 4.2 on 2024-01-23 13:08

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('Course', '0006_remove_course_categorie_delete_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('software_test', 'software_test'), ('devoloper', 'devoloper'), ('Data_Analysis', 'Data_Analysis')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
